### ISSUE TITLE
URGENT Bug: Unable to add email to IG Creation form

### ISSUE THREAD

**Issue by Yoshi275** [usdevs/usc-website#41]
![image](https://user-images.githubusercontent.com/19257264/64399390-d9417f00-d09a-11e9-9d9b-d28e89a4add4.png)
Infinite loading addition of emails, so unable to add emails to IG creation form => unable to request for creation of IGs

**Comment by yeejian-tan** [comment]
Please check, should be fixed. @Yoshi275

**Comment by yeejian-tan** [comment]
Closing this as it is fixed by Firebase rules.
